name: Code Quality

on:
  push:
    branches:
      - main
    paths:
      - '**/*.js'
  pull_request:
    branches:
      - main
    paths:
      - '**/*.js'


jobs:
  lint:
    name: Lint Codebase
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18'  # Updated Node.js version

      - name: Install dependencies
        run: npm install

      - name: Run ESLint
        run: npm run lint
        continue-on-error: true  # Optional: allows workflow to continue even if linting fails


      - name: Generate ESLint report
        run: npm run lint -- --format html --output-file eslint-report.html
        continue-on-error: true  # Optional: allows workflow to continue even if linting fails

      - name: Upload ESLint report
        uses: actions/upload-artifact@v3
        with:
          name: eslint-report
          path: eslint-report.html

     


