name: Java Code Quality Reports

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Set up JDK 11 (or whichever version you are using)
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'  # or 'zulu' as needed
          java-version: '11'

      # Cache Maven dependencies to speed up builds
      - name: Cache Maven dependencies
        uses: actions/cache@v3
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      # Run Maven with Checkstyle, PMD, and SpotBugs, specifying the correct working directory
      - name: Run Maven Checkstyle, PMD, and SpotBugs
        run: mvn verify checkstyle:check pmd:check spotbugs:check -DskipTests
        working-directory: ./nodejsp  # Update this path to match the location of your pom.xml file

      # Upload HTML reports as artifacts
      - name: Upload Checkstyle, PMD, and SpotBugs HTML reports
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: code-quality-reports
          path: |
            nodejsp/target/site/checkstyle.html
            nodejsp/target/site/pmd.html
            nodejsp/target/site/spotbugs.html
