name: Code Quality (C)

on:
  push:
    branches:
      - main
    paths:
      - '**/*.c'
  pull_request:
    branches:
      - main
    paths:
      - '**/*.c'
  workflow_dispatch:

jobs:
  lint:
    name: Lint C Codebase
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Cppcheck
        run: |
          sudo apt-get update
          sudo apt-get install -y cppcheck
      - name: Run Cppcheck
        run: |
          cppcheck --enable=all --inconclusive --xml . 2> cppcheck-report.xml || true
        continue-on-error: true  # Allows workflow to continue even if linting finds issues

      - name: Upload Cppcheck Report
        uses: actions/upload-artifact@v3
        with:
          name: cppcheck-report
          path: cppcheck-report.xml
