name: Java Code Quality Report

on:
  push:
    branches:
      - main
    paths:
      - '**/*.java'
  pull_request:
    branches:
      - main
    paths:
      - '**/*.java'
  workflow_dispatch:   # Enables manual run from the Actions tab

jobs:
  quality-check:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'

      - name: Install Checkstyle
        run: |
          wget https://github.com/checkstyle/checkstyle/releases/download/checkstyle-8.45.1/checkstyle-8.45.1-all.jar -O checkstyle.jar
          wget https://raw.githubusercontent.com/checkstyle/checkstyle/checkstyle-8.45.1/src/main/resources/google_checks.xml -O checkstyle-config.xml

      - name: Run Checkstyle
        run: |
          java -jar checkstyle.jar -c checkstyle-config.xml -f plain -o checkstyle.txt $(find . -name "*.java") || echo "Checkstyle encountered errors." >> checkstyle.txt

      - name: Install SpotBugs
        run: |
          wget https://repo1.maven.org/maven2/com/github/spotbugs/spotbugs/4.5.0/spotbugs-4.5.0.tgz -O spotbugs.tgz
          tar -xzf spotbugs.tgz
          chmod +x ./spotbugs-4.5.0/bin/spotbugs
          rm spotbugs.tgz

      - name: Compile Java Files
        run: |
          find . -name "*.class" -delete
          javac $(find . -name "*.java") || echo "Compilation errors occurred." >> compilation_errors.txt

      - name: Run SpotBugs
        run: |
          ./spotbugs-4.5.0/bin/spotbugs -textui -output spotbugs.txt $(find . -name "*.class") || echo "SpotBugs encountered errors." >> spotbugs.txt

      - name: Calculate Checkstyle Quality Percentage
        run: |
          total_lines=$(wc -l < checkstyle.txt)
          total_violations=$(grep -c 'Line' checkstyle.txt)
          if [ "$total_lines" -gt 0 ]; then
            checkstyle_quality=$(echo "scale=2; (1 - ($total_violations / $total_lines)) * 100" | bc)
          else
            checkstyle_quality=0
          fi
          echo "Checkstyle Quality Percentage: $checkstyle_quality%" >> code-quality-report.html

      - name: Consolidate Reports into a Single File
        run: |
          echo "<html><body><h1>Java Code Quality Report</h1>" > code-quality-report.html
          echo "<h2>Checkstyle Report</h2><pre>" >> code-quality-report.html
          cat checkstyle.txt >> code-quality-report.html
          
          echo "</pre><h2>Compilation Errors</h2><pre>" >> code-quality-report.html
          if [ -f compilation_errors.txt ]; then
            cat compilation_errors.txt >> code-quality-report.html
          else
            echo "No compilation errors." >> code-quality-report.html
          fi

          echo "</pre><h2>SpotBugs Report</h2><pre>" >> code-quality-report.html
          if [ -f spotbugs.txt ]; then
            cat spotbugs.txt >> code-quality-report.html
          else
            echo "No SpotBugs issues detected." >> code-quality-report.html
          fi
          
          echo "</pre><h2>Checkstyle Quality Percentage</h2><p>Checkstyle Quality: $checkstyle_quality%</p>" >> code-quality-report.html
          echo "</body></html>" >> code-quality-report.html

      - name: Upload Consolidated Code Quality Report
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: code-quality-report
          path: code-quality-report.html
