name: Java Code Quality Reports

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Set up JDK 11 (or whichever version you are using)
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'

      # Cache Maven dependencies to speed up builds
      - name: Cache Maven dependencies
        uses: actions/cache@v3
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      # Run Maven with Checkstyle, PMD, and SpotBugs
      - name: Run Maven Checkstyle, PMD, and SpotBugs
        run: mvn clean install checkstyle:check pmd:check spotbugs:check -DskipTests

      # Upload HTML reports as artifacts
      - name: Upload Checkstyle, PMD, and SpotBugs HTML reports
        uses: actions/upload-artifact@v3
        with:
          name: code-quality-reports
          path: |
            target/checkstyle-report.html
            target/pmd-report/pmd.html
            target/spotbugs-report/spotbugs.html
