name: Code Coverage for Python

on:
  push:
    branches:
      - main
    paths:
      - '**/*.py'
  pull_request:
    branches:
      - main
    paths:
      - '**/*.py'
  workflow_dispatch:

jobs:
  test:
    name: Run Tests and Upload Coverage
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set up Python environment
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      # Step 3: Install dependencies from pip (if requirements.txt doesn't exist)
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest pytest-cov  # Ensure pytest and pytest-cov are installed for coverage
          
          # If you have a virtual environment or project-specific dependencies, install them dynamically
          pip freeze > requirements.txt  # Generate the requirements.txt file dynamically

      # Step 4: Run tests and generate coverage reports (XML and HTML)
      - name: Run tests with coverage
        run: |
          pytest --cov=. --cov-report=xml --cov-report=html

      # Step 5: Upload Coverage Reports as Artifacts
      - name: Upload Coverage Reports
        uses: actions/upload-artifact@v3
        with:
          name: python-coverage-report
          path: |
            htmlcov/
            coverage.xml

      # Step 6: Clean up coverage artifacts
      - name: Clean up Coverage Files
        run: |
          rm -rf htmlcov/ .coverage coverage.xml
