name: Java Code Quality Reports

on:
  push:
    branches:
      - main
    paths:
      - '**/*.java'  # Trigger only on Java file changes
  pull_request:
    branches:
      - main
    paths:
      - '**/*.java'  # Trigger only on Java file changes in pull requests

jobs:
  quality-check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'

      - name: Cache Maven dependencies
        uses: actions/cache@v3
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Run Checkstyle
        run: mvn checkstyle:check
        working-directory: ./nodejsp  # Adjust if pom.xml is in a subdirectory

      - name: Run PMD
        run: mvn pmd:check
        working-directory: ./nodejsp

      - name: Run SpotBugs
        run: mvn spotbugs:spotbugs
        working-directory: ./nodejsp

      - name: Upload Code Quality Reports
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: code-quality-reports
          path: |
            nodejsp/target/site/checkstyle.html
            nodejsp/target/site/pmd.html
            nodejsp/target/site/spotbugs.html
