name: Code Quality (C)

on:
  push:
    branches:
      - main
    paths:
      - '**/*.c'
  pull_request:
    branches:
      - main
    paths:
      - '**/*.c'

jobs:
  lint:
    name: Lint C Codebase
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Cppcheck and xsltproc
        run: |
          sudo apt-get update
          sudo apt-get install -y cppcheck xsltproc

      - name: Download Cppcheck HTML XSL stylesheet
        run: |
          wget https://raw.githubusercontent.com/danmar/cppcheck/main/htmlreport/cppcheck-html.xsl -O cppcheck-html.xsl

      - name: Run Cppcheck and Generate XML Report
        run: |
          cppcheck --enable=all --inconclusive --xml . 2> cppcheck-report.xml || true
        continue-on-error: true  # Allows workflow to continue even if linting finds issues

      - name: Convert XML to HTML
        run: |
          xsltproc cppcheck-html.xsl cppcheck-report.xml > cppcheck-report.html

      - name: Upload Cppcheck HTML Report
        uses: actions/upload-artifact@v3
        with:
          name: cppcheck-html-report
          path: cppcheck-report.html
