name: Java Code Quality Reports

on:
  push:
    branches:
      - main
    paths:
      - '**/*.java'
  pull_request:
    branches:
      - main
    paths:
      - '**/*.java'

jobs:
  quality-check:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: nodejsp  # Set globally if `pom.xml` is in `nodejsp`

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'

      - name: Cache Maven dependencies
        uses: actions/cache@v3
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Run Checkstyle
        run: mvn checkstyle:check

      - name: Run PMD
        run: mvn pmd:check

      - name: Run SpotBugs
        run: mvn spotbugs:spotbugs

      - name: Upload Code Quality Reports
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: code-quality-reports
          path: |
            target/site/checkstyle.html
            target/site/pmd.html
            target/site/spotbugs.html
