name: Code Quality (C)

on:
  push:
    branches:
      - main
    paths:
      - '**/*.c'
  pull_request:
    branches:
      - main
    paths:
      - '**/*.c'

jobs:
  lint:
    name: Lint C Codebase
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Cppcheck and HTML Report Tool
        run: |
          sudo apt-get update
          sudo apt-get install -y cppcheck
          sudo apt-get install -y python3-pip
          pip3 install cppcheck-htmlreport  # Install the HTML report generator

      - name: Run Cppcheck Analysis
        run: |
          cppcheck --enable=all --inconclusive --xml . 2> cppcheck-report.xml || true
        continue-on-error: true  # Allows workflow to continue even if linting finds issues

      - name: Generate Cppcheck HTML Report
        run: |
          cppcheck-htmlreport --file=cppcheck-report.xml --report-dir=cppcheck-html-report --source-dir=.
        continue-on-error: true

      - name: Upload Cppcheck HTML Report
        uses: actions/upload-artifact@v3
        with:
          name: cppcheck-html-report
          path: cppcheck-html-report/
