name: Code Quality (C)

on:
  push:
    branches:
      - main
    paths:
      - '**/*.c'
  pull_request:
    branches:
      - main
    paths:
      - '**/*.c'

jobs:
  lint:
    name: Lint C Codebase
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Cppcheck
        run: |
          sudo apt-get update
          sudo apt-get install -y cppcheck

      - name: Run Cppcheck and Generate HTML Report
        run: |
          cppcheck --enable=all --inconclusive --xml --xml-version=2 . 2> cppcheck-report.xml || true
          cppcheck-htmlreport --file=cppcheck-report.xml --report-dir=cppcheck-html-report --source-dir=. || true
        continue-on-error: true

      - name: Upload Cppcheck HTML Report
        uses: actions/upload-artifact@v3
        with:
          name: cppcheck-html-report
          path: cppcheck-html-report/
