name: ESLint Code Quality Report

on:
  push:
    paths:
      - '**/*.js' # Trigger only on .js file changes
  pull_request:
    paths:
      - '**/*.js' # Trigger only on .js file changes
  workflow_dispatch:

jobs:
  lint:
    name: Run ESLint and Generate HTML Report
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '16' # Specify Node.js version

    - name: Install Dependencies
      run: npm install

    - name: Install ESLint HTML Reporter
      run: npm install eslint-html-reporter --save-dev

    - name: Run ESLint and Generate HTML Report
      id: eslint
      run: |
        # Run ESLint and output results to JSON
        npx eslint '**/*.js' -f json > eslint-report.json
        
        # Convert JSON to HTML using the ESLint HTML Reporter
        npx eslint-html-reporter -o eslint-report.html -f eslint-report.json

    - name: Upload ESLint HTML Report
      uses: actions/upload-artifact@v3
      with:
        name: eslint-html-report
        path: eslint-report.html
