name: ESLint Code Quality Report

on:
  push:
    paths:
      - '**/*.js'
  pull_request:
    paths:
      - '**/*.js'
  workflow_dispatch:

jobs:
  lint:
    name: Run ESLint and Generate HTML Report
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'

    - name: Install Dependencies
      run: |
        npm install eslint eslint-formatter-html --save-dev

    - name: Run ESLint and Generate HTML Report
      run: |
        npx eslint '**/*.js' -f html -o eslint-report.html || {
          echo "ESLint failed. Printing debug info...";
          exit 1;
        }

    - name: Upload ESLint HTML Report
      uses: actions/upload-artifact@v3
      with:
        name: eslint-html-report
        path: eslint-report.html
