name: ESLint Code Quality Report

on:
  push:
    paths:
      - '**/*.js'
  pull_request:
    paths:
      - '**/*.js'
  workflow_dispatch:

jobs:
  lint:
    name: Run ESLint and Generate HTML Report
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18' # Ensure structuredClone is supported

    - name: Install Dependencies
      run: npm install

    - name: Run ESLint and Generate HTML Report
      id: eslint
      run: |
        # Run ESLint and output results to JSON
        npx eslint '**/*.js' -f json > eslint-report.json || {
          echo "ESLint failed. Printing debug info...";
          cat eslint-report.json || echo "No ESLint report generated.";
          exit 1;
        }

        # Convert JSON to HTML using eslint-html-reporter
        npx eslint-html-reporter -o eslint-report.html -f eslint-report.json

    - name: Upload ESLint HTML Report
      uses: actions/upload-artifact@v3
      with:
        name: eslint-html-report
        path: eslint-report.html
